[project]
name = "ai-support-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Harveen Kaur", email = "harveenkaur282@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bedrock-agentcore>=1.23.1",
    "bedrock-agentcore-starter-toolkit>=0.3.13",
    "boto3",
    "chardet>=6.0.0.post1",
    "nest-asyncio>=1.6.0",
    "playwright>=1.58.0",
    "PyYAML",
    "strands-agents>=1.56.0",
    "strands-agents-tools>=0.8.9",
    "urllib3>=2.6.3",
]

[project.scripts]
ai-support-agent = "ai_support_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
